PythonProject/PythonProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve #需要导入
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),#这部分很重要
    url(r'^UserInfo/', include('apps.UserInfo.urls', namespace='UserInfo')),  # 用户模块
    url(r'^Area/', include('apps.Area.urls', namespace='Area')),  # 区域模块
    url(r'^LookingFor/', include('apps.LookingFor.urls', namespace='LookingFor')),  # 寻物启事模块
    url(r'^LostFound/', include('apps.LostFound.urls', namespace='LostFound')),  # 失物招领模块
    url(r'^Claim/', include('apps.Claim.urls', namespace='Claim')),  # 认领模块
    url(r'^Praise/', include('apps.Praise.urls', namespace='Praise')),  # 表扬模块
    url(r'^Notice/', include('apps.Notice.urls', namespace='Notice')),  # 站内通知模块

    url(r'^', include("apps.Index.urls", namespace="Index")),  # 首页模块

    url(r'^tinymce/', include('tinymce.urls')),
]

PythonProject/apps/Claim/urls.py
from apps.Claim.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, FrontModifyView, ListAllView
from django.conf.urls import url

# 正在部署的应用的名称
app_name = 'Claim'

urlpatterns = [
    url(r'^frontAdd$', FrontAddView.as_view(), name='frontAdd'),  # 前台添加
    url(r'^frontModify/(?P<claimId>.+)$', FrontModifyView.as_view(), name='frontModify'),  # 前台更新
    url(r'^frontList$', FrontListView.as_view(), name='frontList'),  # 前台查询列表
    url(r'^frontShow/(?P<claimId>.+)$', FrontShowView.as_view(), name='frontShow'),  # 前台显示详情页
    url(r'^listAll', ListAllView.as_view(), name='listAll'),  # 前台查询所有信息

    url(r'^update/(?P<claimId>.+)$', UpdateView.as_view(), name='update'),  # Ajax方式更新记录

    url(r'^add$', AddView.as_view(), name='add'),  # 后台添加
    url(r'^backModify/(?P<claimId>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新
    url(r'^list$', ListView.as_view(), name='list'),  # 后台信息列表
    url(r'^deletes$', DeletesView.as_view(), name="deletes"),  # 删除记录信息
    url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出信息到excel并下载
]

PythonProject/apps/Index/urls.py
from django.conf.urls import url
from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,ChangePasswordView

# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    url(r'^login$', LoginView.as_view(), name="login"),  # 后台登录
    url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    url(r'^main$', MainView.as_view(), name='main'),  # 后台主页面
    url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword')  # 管理员修改密码
]

PythonProject/apps/Claim/models.py
from django.db import models
from apps.LostFound.models import LostFound


class Claim(models.Model):
    claimId = models.AutoField(primary_key=True, verbose_name='认领id')
    lostFoundObj = models.ForeignKey(LostFound,  db_column='lostFoundObj', on_delete=models.PROTECT, verbose_name='招领信息')
    personName = models.CharField(max_length=20, default='', verbose_name='认领人')
    claimTime = models.CharField(max_length=20, default='', verbose_name='认领时间')
    contents = models.CharField(max_length=500, default='', verbose_name='描述说明')
    addTime = models.CharField(max_length=20, default='', verbose_name='发布时间')

    class Meta:
        db_table = 't_Claim'
        verbose_name = '认领信息'
        verbose_name_plural = verbose_name

    def getJsonObj(self):
        claim = {
            'claimId': self.claimId,
            'lostFoundObj': self.lostFoundObj.title,
            'lostFoundObjPri': self.lostFoundObj.lostFoundId,
            'personName': self.personName,
            'claimTime': self.claimTime,
            'contents': self.contents,
            'addTime': self.addTime,
        }
        return claim


PythonProject/apps/Claim/views.py
from django.views.generic import View
from apps.BaseView import BaseView
from django.shortcuts import render
from django.core.paginator import Paginator
from apps.Claim.models import Claim
from apps.LostFound.models import LostFound
from django.http import JsonResponse
from django.http import FileResponse
from apps.BaseView import ImageFormatException
from django.conf import settings
import pandas as pd
import os


class FrontAddView(BaseView):  # 前台认领添加
    def get(self,request):
        lostFounds = LostFound.objects.all()  # 获取所有失物招领
        context = {
            'lostFounds': lostFounds,
        }

        # 使用模板
        return render(request, 'Claim/claim_frontAdd.html', context)

    def post(self, request):
        claim = Claim() # 新建一个认领对象然后获取参数
        claim.lostFoundObj = LostFound.objects.get(lostFoundId=request.POST.get('claim.lostFoundObj.lostFoundId'))
        claim.personName = request.POST.get('claim.personName')
        claim.claimTime = request.POST.get('claim.claimTime')
        claim.contents = request.POST.get('claim.contents')
        claim.addTime = request.POST.get('claim.addTime')
        claim.save() # 保存认领信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class FrontModifyView(BaseView):  # 前台修改认领
    def get(self, request, claimId):
        context = {'claimId': claimId}
        return render(request, 'Claim/claim_frontModify.html', context)


class FrontListView(BaseView):  # 前台认领查询列表
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        lostFoundObj_lostFoundId = self.getIntParam(request, 'lostFoundObj.lostFoundId')
        personName = self.getStrParam(request, 'personName')
        claimTime = self.getStrParam(request, 'claimTime')
        # 然后条件组合查询过滤
        claims = Claim.objects.all()
        if lostFoundObj_lostFoundId != '0':
            claims = claims.filter(lostFoundObj=lostFoundObj_lostFoundId)
        if personName != '':
            claims = claims.filter(personName__contains=personName)
        if claimTime != '':
            claims = claims.filter(claimTime__contains=claimTime)
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(claims, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        claims_page = self.paginator.page(self.currentPage)

        # 获取所有失物招领
        lostFounds = LostFound.objects.all()
        # 构造模板需要的参数
        context = {
            'lostFounds': lostFounds,
            'claims_page': claims_page,
            'lostFoundObj_lostFoundId': int(lostFoundObj_lostFoundId),
            'personName': personName,
            'claimTime': claimTime,
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList,
        }
        # 渲染模板界面
        return render(request, 'Claim/claim_frontquery_result.html', context)


class FrontShowView(View):  # 前台显示认领详情页
    def get(self, request, claimId):
        # 查询需要显示的认领对象
        claim = Claim.objects.get(claimId=claimId)
        context = {
            'claim': claim
        }
        # 渲染模板显示
        return render(request, 'Claim/claim_frontshow.html', context)


class ListAllView(View): # 前台查询所有认领
    def get(self,request):
        claims = Claim.objects.all()
        claimList = []
        for claim in claims:
            claimObj = {
                'claimId': claim.claimId,
            }
            claimList.append(claimObj)
        return JsonResponse(claimList, safe=False)


class UpdateView(BaseView):  # Ajax方式认领更新
    def get(self, request, claimId):
        # GET方式请求查询认领对象并返回认领json格式
        claim = Claim.objects.get(claimId=claimId)
        return JsonResponse(claim.getJsonObj())

    def post(self, request, claimId):
        # POST方式提交认领修改信息更新到数据库
        claim = Claim.objects.get(claimId=claimId)
        claim.lostFoundObj = LostFound.objects.get(lostFoundId=request.POST.get('claim.lostFoundObj.lostFoundId'))
        claim.personName = request.POST.get('claim.personName')
        claim.claimTime = request.POST.get('claim.claimTime')
        claim.contents = request.POST.get('claim.contents')
        claim.addTime = request.POST.get('claim.addTime')
        claim.save()
        return JsonResponse({'success': True, 'message': '保存成功'})

class AddView(BaseView):  # 后台认领添加
    def get(self,request):
        lostFounds = LostFound.objects.all()  # 获取所有失物招领
        context = {
            'lostFounds': lostFounds,
        }

        # 渲染显示模板界面
        return render(request, 'Claim/claim_add.html', context)

    def post(self, request):
        # POST方式处理图书添加业务
        claim = Claim() # 新建一个认领对象然后获取参数
        claim.lostFoundObj = LostFound.objects.get(lostFoundId=request.POST.get('claim.lostFoundObj.lostFoundId'))
        claim.personName = request.POST.get('claim.personName')
        claim.claimTime = request.POST.get('claim.claimTime')
        claim.contents = request.POST.get('claim.contents')
        claim.addTime = request.POST.get('claim.addTime')
        claim.save() # 保存认领信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class BackModifyView(BaseView):  # 后台更新认领
    def get(self, request, claimId):
        context = {'claimId': claimId}
        return render(request, 'Claim/claim_modify.html', context)


class ListView(BaseView):  # 后台认领列表
    def get(self, request):
        # 使用模板
        return render(request, 'Claim/claim_query_result.html')

    def post(self, request):
        # 获取当前要显示第几页和每页几条数据
        self.getPageAndSize(request)
        # 收集查询参数
        lostFoundObj_lostFoundId = self.getIntParam(request, 'lostFoundObj.lostFoundId')
        personName = self.getStrParam(request, 'personName')
        claimTime = self.getStrParam(request, 'claimTime')
        # 然后条件组合查询过滤
        claims = Claim.objects.all()
        if lostFoundObj_lostFoundId != '0':
            claims = claims.filter(lostFoundObj=lostFoundObj_lostFoundId)
        if personName != '':
            claims = claims.filter(personName__contains=personName)
        if claimTime != '':
            claims = claims.filter(claimTime__contains=claimTime)
        # 利用Paginator对查询结果集分页
        self.paginator = Paginator(claims, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        claims_page = self.paginator.page(self.currentPage)
        # 查询的结果集转换为列表
        claimList = []
        for claim in claims_page:
            claim = claim.getJsonObj()
            claimList.append(claim)
        # 构造模板页面需要的参数
        claim_res = {
            'rows': claimList,
            'total': self.recordNumber,
        }
        # 渲染模板页面显示
        return JsonResponse(claim_res, json_dumps_params={'ensure_ascii':False})

class DeletesView(BaseView):  # 删除认领信息
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        claimIds = self.getStrParam(request, 'claimIds')
        claimIds = claimIds.split(',')
        count = 0
        try:
            for claimId in claimIds:
                Claim.objects.get(claimId=claimId).delete()
                count = count + 1
            message = '%s条记录删除成功！' % count
            success = True
        except Exception as e:
            message = '数据库外键约束删除失败！'
            success = False
        return JsonResponse({'success': success, 'message': message})


class OutToExcelView(BaseView):  # 导出认领信息到excel并下载
    def get(self, request):
        # 收集查询参数
        lostFoundObj_lostFoundId = self.getIntParam(request, 'lostFoundObj.lostFoundId')
        personName = self.getStrParam(request, 'personName')
        claimTime = self.getStrParam(request, 'claimTime')
        # 然后条件组合查询过滤
        claims = Claim.objects.all()
        if lostFoundObj_lostFoundId != '0':
            claims = claims.filter(lostFoundObj=lostFoundObj_lostFoundId)
        if personName != '':
            claims = claims.filter(personName__contains=personName)
        if claimTime != '':
            claims = claims.filter(claimTime__contains=claimTime)
        #将查询结果集转换成列表
        claimList = []
        for claim in claims:
            claim = claim.getJsonObj()
            claimList.append(claim)
        # 利用pandas实现数据的导出功能
        pf = pd.DataFrame(claimList)
        # 设置要导入到excel的列
        columns_map = {
            'claimId': '认领id',
            'lostFoundObj': '招领信息',
            'personName': '认领人',
            'claimTime': '认领时间',
            'addTime': '发布时间',
        }
        pf = pf[columns_map.keys()]
        pf.rename(columns=columns_map, inplace=True)
        # 将空的单元格替换为空字符
        pf.fillna('', inplace=True)
        #设定文件名和导出路径
        filename = 'claims.xlsx'
        # 这个路径可以在settings中设置也可以直接手动输入
        root_path = settings.MEDIA_ROOT + '/output/'
        file_path = os.path.join(root_path, filename)
        pf.to_excel(file_path, encoding='utf-8', index=False)
        # 将生成的excel文件输出到网页下载
        file = open(file_path, 'rb')
        response = FileResponse(file)
        response['Content-Type'] = 'application/octet-stream'
        response['Content-Disposition'] = 'attachment;filename="claims.xlsx"'
        return response


PythonProject/templates/Claim/claim_frontquery_result.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>认领查询</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
<div class="container">
{% include 'header.html' %}
	<div class="row"> 
	<div class="col-md-3 wow fadeInLeft">
		<div class="page-header">
    		<h1>认领查询</h1>
		</div>
		<form name="claimQueryForm" id="claimQueryForm" action="{% url 'Claim:frontList' %}" class="mar_t15" method="post">
			 {% csrf_token %}
            <div class="form-group">
            	<label for="lostFoundObj_lostFoundId">招领信息：</label>
                <select id="lostFoundObj_lostFoundId" name="lostFoundObj.lostFoundId" class="form-control">
                	<option value="0">不限制</option>
                    {% for lostFound in lostFounds %}
                        {% if lostFound.lostFoundId == lostFoundObj_lostFoundId %}
                             <option value="{{ lostFound.lostFoundId }}" selected>{{ lostFound.title }}</option>
                        {% else %}
                            <option value="{{ lostFound.lostFoundId }}">{{ lostFound.title }}</option>
                        {% endif %}
                    {% endfor %}
 			</select>
            </div>
			<div class="form-group">
				<label for="personName">认领人:</label>
				<input type="text" id="personName" name="personName" value="{{ personName }}" class="form-control" placeholder="请输入认领人">
			</div>
			<div class="form-group">
				<label for="claimTime">认领时间:</label>
				<input type="text" id="claimTime" name="claimTime" class="form-control"  placeholder="请选择认领时间" value="{{ claimTime }}" onclick="SelectDate(this,'yyyy-MM-dd')" />
			</div>
            <input type=hidden name=currentPage value="{{ currentPage }}" />
            <button type="submit" class="btn btn-primary">查询</button>
        </form>
	</div>

		<div class="col-md-9 wow fadeInDown" data-wow-duration="0.5s">
			<div>
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
			    	<li><a href="{% url 'Index:index' %}">首页</a></li>
			    	<li role="presentation" class="active"><a href="#claimListPanel" aria-controls="claimListPanel" role="tab" data-toggle="tab">认领列表</a></li>
			    	<li role="presentation" ><a href="{% url 'Claim:frontAdd' %}" style="display:none;">添加认领</a></li>
				</ul>
			  	<!-- Tab panes -->
			  	<div class="tab-content">
				    <div role="tabpanel" class="tab-pane active" id="claimListPanel">
				    		<div class="row">
				    			<div class="col-md-12 top5">
				    				<div class="table-responsive">
				    				<table class="table table-condensed table-hover">
				    					<tr class="success bold"><td>序号</td><td>认领id</td><td>招领信息</td><td>认领人</td><td>认领时间</td><td>发布时间</td><td>操作</td></tr>
                                        {% for claim in claims_page %}
 										<tr>
 											<td>{{ startIndex|add:forloop.counter }}</td>
 											<td>{{ claim.claimId }}</td>
 											<td>{{ claim.lostFoundObj.title }}</td>
 											<td>{{ claim.personName }}</td>
 											<td>{{ claim.claimTime }}</td>
 											<td>{{ claim.addTime }}</td>
 											<td>
 												<a href="{% url 'Claim:frontShow' claim.claimId  %}"><i class="fa fa-info"></i>&nbsp;查看</a>&nbsp;
 												<a href="#" onclick="claimEdit('{{ claim.claimId }}');" style="display:none;"><i class="fa fa-pencil fa-fw"></i>编辑</a>&nbsp;
 												<a href="#" onclick="claimDelete('{{ claim.claimId }}');" style="display:none;"><i class="fa fa-trash-o fa-fw"></i>删除</a>
 											</td> 
 										</tr>
 										{% endfor %}
				    				</table>
				    				</div>
				    			</div>
				    		</div>

				    		<div class="row">
					            <div class="col-md-12">
						            <nav class="pull-left">
						                <ul class="pagination">
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:-1 }},{{ totalPage }}>);" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                                            {% for page in pageList %}
                                            {% if currentPage == page %}
						                        <li class="active"><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
						                    {% else %}
                                                <li><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
                                            {% endif %}
                                            {% endfor %}
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:1 }},{{ totalPage }});"><span aria-hidden="true">&raquo;</span></a></li>
						                </ul>
						            </nav>
						            <div class="pull-right" style="line-height:75px;" >共有{{ recordNumber }}条记录，当前第{{ currentPage }}/{{ totalPage }} 页</div>
					            </div>
				            </div> 
				    </div>
				</div>
			</div>
		</div>
		</div>
	</div> 
<div id="claimEditDialog" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><i class="fa fa-edit"></i>&nbsp;认领信息编辑</h4>
      </div>
      <div class="modal-body" style="height:450px; overflow: scroll;">
      	<form class="form-horizontal" name="claimEditForm" id="claimEditForm" enctype="multipart/form-data" method="post"  class="mar_t15">
		    {% csrf_token %}
		  <div class="form-group">
			 <label for="claim_claimId_edit" class="col-md-3 text-right">认领id:</label>
			 <div class="col-md-9"> 
			 	<input type="text" id="claim_claimId_edit" name="claim.claimId" class="form-control" placeholder="请输入认领id" readOnly>
			 </div>
		  </div> 
		  <div class="form-group">
		  	 <label for="claim_lostFoundObj_lostFoundId_edit" class="col-md-3 text-right">招领信息:</label>
		  	 <div class="col-md-9">
			    <select id="claim_lostFoundObj_lostFoundId_edit" name="claim.lostFoundObj.lostFoundId" class="form-control">
                    {% for lostFound in lostFounds %}
                        <option value="{{ lostFoundObj.lostFoundId }}">{{ lostFoundObj.title }}</option>
                    {% endfor %}
			    </select>
		  	 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="claim_personName_edit" class="col-md-3 text-right">认领人:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="claim_personName_edit" name="claim.personName" class="form-control" placeholder="请输入认领人">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="claim_claimTime_edit" class="col-md-3 text-right">认领时间:</label>
		  	 <div class="col-md-9">
                <div class="input-group date claim_claimTime_edit col-md-12" data-link-field="claim_claimTime_edit">
                    <input class="form-control" id="claim_claimTime_edit" name="claim.claimTime" size="16" type="text" value="" placeholder="请选择认领时间" readonly>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                </div>
		  	 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="claim_contents_edit" class="col-md-3 text-right">描述说明:</label>
		  	 <div class="col-md-9">
			    <textarea id="claim_contents_edit" name="claim.contents" rows="8" class="form-control" placeholder="请输入描述说明"></textarea>
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="claim_addTime_edit" class="col-md-3 text-right">发布时间:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="claim_addTime_edit" name="claim.addTime" class="form-control" placeholder="请输入发布时间">
			 </div>
		  </div>
		</form> 
	    <style>#claimEditForm .form-group {margin-bottom:5px;}  </style>
      </div>
      <div class="modal-footer"> 
      	<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
      	<button type="button" class="btn btn-primary" onclick="ajaxClaimModify();">提交</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jsdate.js' %}"></script>
<script>
/*跳转到查询结果的某页*/
function GoToPage(currentPage,totalPage) {
    if(currentPage==0) return;
    if(currentPage>totalPage) return;
    document.claimQueryForm.currentPage.value = currentPage;
    document.claimQueryForm.submit();
}

/*可以直接跳转到某页*/
function changepage(totalPage)
{
    var pageValue=document.claimQueryForm.pageValue.value;
    if(pageValue>totalPage) {
        alert('你输入的页码超出了总页数!');
        return ;
    }
    document.claimQueryForm.currentPage.value = pageValue;
    documentclaimQueryForm.submit();
}

/*弹出修改认领界面并初始化数据*/
function claimEdit(claimId) {
	$.ajax({
		url :  '/Claim/update/' + claimId,
		type : "get",
		dataType: "json",
		success : function (claim, response, status) {
			if (claim) {
				$("#claim_claimId_edit").val(claim.claimId);
				$.ajax({
					url: "{% url 'LostFound:listAll' %}",
					type: "get",
					success: function(lostFounds,response,status) { 
						$("#claim_lostFoundObj_lostFoundId_edit").empty();
						var html="";
		        		$(lostFounds).each(function(i,lostFound){
		        			html += "<option value='" + lostFound.lostFoundId + "'>" + lostFound.title + "</option>";
		        		});
		        		$("#claim_lostFoundObj_lostFoundId_edit").html(html);
		        		$("#claim_lostFoundObj_lostFoundId_edit").val(claim.lostFoundObjPri);
					}
				});
				$("#claim_personName_edit").val(claim.personName);
				$("#claim_claimTime_edit").val(claim.claimTime);
				$("#claim_contents_edit").val(claim.contents);
				$("#claim_addTime_edit").val(claim.addTime);
				$('#claimEditDialog').modal('show');
			} else {
				alert("获取信息失败！");
			}
		}
	});
}

/*删除认领信息*/
function claimDelete(claimId) {
    var csrf = $('input[name="csrfmiddlewaretoken"]').val();
	if(confirm("确认删除这个记录")) {
		$.ajax({
			type : "POST",
			url : "/Claim/deletes",
			data : {
				claimIds : claimId,
                "csrfmiddlewaretoken": csrf
			},
			success : function (obj) {
				if (obj.success) {
					alert("删除成功");
					$("#claimQueryForm").submit();
					//location.href= basePath + "Claim/frontlist";
				}
				else 
					alert(obj.message);
			},
		});
	}
}

/*ajax方式提交认领信息表单给服务器端修改*/
function ajaxClaimModify() {
	$.ajax({
		url :   '/Claim/update/' + $("#claim_claimId_edit").val(),
		type : "post",
		dataType: "json",
		data: new FormData($("#claimEditForm")[0]),
		success : function (obj, response, status) {
            if(obj.success){
                alert("信息修改成功！");
                $("#claimQueryForm").submit();
            }else{
                alert(obj.message);
            } 
		},
		processData: false,
		contentType: false,
	});
}

$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();

    /*认领时间组件*/
    $('.claim_claimTime_edit').datetimepicker({
    	language:  'zh-CN',  //语言
    	format: 'yyyy-mm-dd hh:ii:ss',
    	weekStart: 1,
    	todayBtn:  1,
    	autoclose: 1,
    	minuteStep: 1,
    	todayHighlight: 1,
    	startView: 2,
    	forceParse: 0
    });
})
</script>
</body>
</html>
