PythonProject/PythonProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve #需要导入
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),#这部分很重要
    url(r'^UserInfo/', include('apps.UserInfo.urls', namespace='UserInfo')),  # 用户模块
    url(r'^Area/', include('apps.Area.urls', namespace='Area')),  # 区域模块
    url(r'^LookingFor/', include('apps.LookingFor.urls', namespace='LookingFor')),  # 寻物启事模块
    url(r'^LostFound/', include('apps.LostFound.urls', namespace='LostFound')),  # 失物招领模块
    url(r'^Claim/', include('apps.Claim.urls', namespace='Claim')),  # 认领模块
    url(r'^Praise/', include('apps.Praise.urls', namespace='Praise')),  # 表扬模块
    url(r'^Notice/', include('apps.Notice.urls', namespace='Notice')),  # 站内通知模块

    url(r'^', include("apps.Index.urls", namespace="Index")),  # 首页模块

    url(r'^tinymce/', include('tinymce.urls')),
]

PythonProject/apps/Index/urls.py
from django.conf.urls import url
from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,ChangePasswordView

# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    url(r'^login$', LoginView.as_view(), name="login"),  # 后台登录
    url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    url(r'^main$', MainView.as_view(), name='main'),  # 后台主页面
    url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword')  # 管理员修改密码
]

PythonProject/apps/Praise/urls.py
from apps.Praise.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, FrontModifyView, ListAllView
from django.conf.urls import url

# 正在部署的应用的名称
app_name = 'Praise'

urlpatterns = [
    url(r'^frontAdd$', FrontAddView.as_view(), name='frontAdd'),  # 前台添加
    url(r'^frontModify/(?P<praiseId>.+)$', FrontModifyView.as_view(), name='frontModify'),  # 前台更新
    url(r'^frontList$', FrontListView.as_view(), name='frontList'),  # 前台查询列表
    url(r'^frontShow/(?P<praiseId>.+)$', FrontShowView.as_view(), name='frontShow'),  # 前台显示详情页
    url(r'^listAll', ListAllView.as_view(), name='listAll'),  # 前台查询所有信息

    url(r'^update/(?P<praiseId>.+)$', UpdateView.as_view(), name='update'),  # Ajax方式更新记录

    url(r'^add$', AddView.as_view(), name='add'),  # 后台添加
    url(r'^backModify/(?P<praiseId>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新
    url(r'^list$', ListView.as_view(), name='list'),  # 后台信息列表
    url(r'^deletes$', DeletesView.as_view(), name="deletes"),  # 删除记录信息
    url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出信息到excel并下载
]

PythonProject/apps/Praise/models.py
from django.db import models
from apps.LostFound.models import LostFound


class Praise(models.Model):
    praiseId = models.AutoField(primary_key=True, verbose_name='表扬id')
    lostFoundObj = models.ForeignKey(LostFound,  db_column='lostFoundObj', on_delete=models.PROTECT, verbose_name='招领信息')
    title = models.CharField(max_length=40, default='', verbose_name='标题')
    contents = models.CharField(max_length=300, default='', verbose_name='表扬内容')
    addTime = models.CharField(max_length=20, default='', verbose_name='表扬时间')

    class Meta:
        db_table = 't_Praise'
        verbose_name = '表扬信息'
        verbose_name_plural = verbose_name

    def getJsonObj(self):
        praise = {
            'praiseId': self.praiseId,
            'lostFoundObj': self.lostFoundObj.title,
            'lostFoundObjPri': self.lostFoundObj.lostFoundId,
            'title': self.title,
            'contents': self.contents,
            'addTime': self.addTime,
        }
        return praise


PythonProject/apps/Praise/views.py
from django.views.generic import View
from apps.BaseView import BaseView
from django.shortcuts import render
from django.core.paginator import Paginator
from apps.Praise.models import Praise
from apps.LostFound.models import LostFound
from django.http import JsonResponse
from django.http import FileResponse
from apps.BaseView import ImageFormatException
from django.conf import settings
import pandas as pd
import os


class FrontAddView(BaseView):  # 前台表扬添加
    def get(self,request):
        lostFounds = LostFound.objects.all()  # 获取所有失物招领
        context = {
            'lostFounds': lostFounds,
        }

        # 使用模板
        return render(request, 'Praise/praise_frontAdd.html', context)

    def post(self, request):
        praise = Praise() # 新建一个表扬对象然后获取参数
        praise.lostFoundObj = LostFound.objects.get(lostFoundId=request.POST.get('praise.lostFoundObj.lostFoundId'))
        praise.title = request.POST.get('praise.title')
        praise.contents = request.POST.get('praise.contents')
        praise.addTime = request.POST.get('praise.addTime')
        praise.save() # 保存表扬信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class FrontModifyView(BaseView):  # 前台修改表扬
    def get(self, request, praiseId):
        context = {'praiseId': praiseId}
        return render(request, 'Praise/praise_frontModify.html', context)


class FrontListView(BaseView):  # 前台表扬查询列表
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        lostFoundObj_lostFoundId = self.getIntParam(request, 'lostFoundObj.lostFoundId')
        title = self.getStrParam(request, 'title')
        addTime = self.getStrParam(request, 'addTime')
        # 然后条件组合查询过滤
        praises = Praise.objects.all()
        if lostFoundObj_lostFoundId != '0':
            praises = praises.filter(lostFoundObj=lostFoundObj_lostFoundId)
        if title != '':
            praises = praises.filter(title__contains=title)
        if addTime != '':
            praises = praises.filter(addTime__contains=addTime)
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(praises, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        praises_page = self.paginator.page(self.currentPage)

        # 获取所有失物招领
        lostFounds = LostFound.objects.all()
        # 构造模板需要的参数
        context = {
            'lostFounds': lostFounds,
            'praises_page': praises_page,
            'lostFoundObj_lostFoundId': int(lostFoundObj_lostFoundId),
            'title': title,
            'addTime': addTime,
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList,
        }
        # 渲染模板界面
        return render(request, 'Praise/praise_frontquery_result.html', context)


class FrontShowView(View):  # 前台显示表扬详情页
    def get(self, request, praiseId):
        # 查询需要显示的表扬对象
        praise = Praise.objects.get(praiseId=praiseId)
        context = {
            'praise': praise
        }
        # 渲染模板显示
        return render(request, 'Praise/praise_frontshow.html', context)


class ListAllView(View): # 前台查询所有表扬
    def get(self,request):
        praises = Praise.objects.all()
        praiseList = []
        for praise in praises:
            praiseObj = {
                'praiseId': praise.praiseId,
                'title': praise.title,
            }
            praiseList.append(praiseObj)
        return JsonResponse(praiseList, safe=False)


class UpdateView(BaseView):  # Ajax方式表扬更新
    def get(self, request, praiseId):
        # GET方式请求查询表扬对象并返回表扬json格式
        praise = Praise.objects.get(praiseId=praiseId)
        return JsonResponse(praise.getJsonObj())

    def post(self, request, praiseId):
        # POST方式提交表扬修改信息更新到数据库
        praise = Praise.objects.get(praiseId=praiseId)
        praise.lostFoundObj = LostFound.objects.get(lostFoundId=request.POST.get('praise.lostFoundObj.lostFoundId'))
        praise.title = request.POST.get('praise.title')
        praise.contents = request.POST.get('praise.contents')
        praise.addTime = request.POST.get('praise.addTime')
        praise.save()
        return JsonResponse({'success': True, 'message': '保存成功'})

class AddView(BaseView):  # 后台表扬添加
    def get(self,request):
        lostFounds = LostFound.objects.all()  # 获取所有失物招领
        context = {
            'lostFounds': lostFounds,
        }

        # 渲染显示模板界面
        return render(request, 'Praise/praise_add.html', context)

    def post(self, request):
        # POST方式处理图书添加业务
        praise = Praise() # 新建一个表扬对象然后获取参数
        praise.lostFoundObj = LostFound.objects.get(lostFoundId=request.POST.get('praise.lostFoundObj.lostFoundId'))
        praise.title = request.POST.get('praise.title')
        praise.contents = request.POST.get('praise.contents')
        praise.addTime = request.POST.get('praise.addTime')
        praise.save() # 保存表扬信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class BackModifyView(BaseView):  # 后台更新表扬
    def get(self, request, praiseId):
        context = {'praiseId': praiseId}
        return render(request, 'Praise/praise_modify.html', context)


class ListView(BaseView):  # 后台表扬列表
    def get(self, request):
        # 使用模板
        return render(request, 'Praise/praise_query_result.html')

    def post(self, request):
        # 获取当前要显示第几页和每页几条数据
        self.getPageAndSize(request)
        # 收集查询参数
        lostFoundObj_lostFoundId = self.getIntParam(request, 'lostFoundObj.lostFoundId')
        title = self.getStrParam(request, 'title')
        addTime = self.getStrParam(request, 'addTime')
        # 然后条件组合查询过滤
        praises = Praise.objects.all()
        if lostFoundObj_lostFoundId != '0':
            praises = praises.filter(lostFoundObj=lostFoundObj_lostFoundId)
        if title != '':
            praises = praises.filter(title__contains=title)
        if addTime != '':
            praises = praises.filter(addTime__contains=addTime)
        # 利用Paginator对查询结果集分页
        self.paginator = Paginator(praises, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        praises_page = self.paginator.page(self.currentPage)
        # 查询的结果集转换为列表
        praiseList = []
        for praise in praises_page:
            praise = praise.getJsonObj()
            praiseList.append(praise)
        # 构造模板页面需要的参数
        praise_res = {
            'rows': praiseList,
            'total': self.recordNumber,
        }
        # 渲染模板页面显示
        return JsonResponse(praise_res, json_dumps_params={'ensure_ascii':False})

class DeletesView(BaseView):  # 删除表扬信息
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        praiseIds = self.getStrParam(request, 'praiseIds')
        praiseIds = praiseIds.split(',')
        count = 0
        try:
            for praiseId in praiseIds:
                Praise.objects.get(praiseId=praiseId).delete()
                count = count + 1
            message = '%s条记录删除成功！' % count
            success = True
        except Exception as e:
            message = '数据库外键约束删除失败！'
            success = False
        return JsonResponse({'success': success, 'message': message})


class OutToExcelView(BaseView):  # 导出表扬信息到excel并下载
    def get(self, request):
        # 收集查询参数
        lostFoundObj_lostFoundId = self.getIntParam(request, 'lostFoundObj.lostFoundId')
        title = self.getStrParam(request, 'title')
        addTime = self.getStrParam(request, 'addTime')
        # 然后条件组合查询过滤
        praises = Praise.objects.all()
        if lostFoundObj_lostFoundId != '0':
            praises = praises.filter(lostFoundObj=lostFoundObj_lostFoundId)
        if title != '':
            praises = praises.filter(title__contains=title)
        if addTime != '':
            praises = praises.filter(addTime__contains=addTime)
        #将查询结果集转换成列表
        praiseList = []
        for praise in praises:
            praise = praise.getJsonObj()
            praiseList.append(praise)
        # 利用pandas实现数据的导出功能
        pf = pd.DataFrame(praiseList)
        # 设置要导入到excel的列
        columns_map = {
            'praiseId': '表扬id',
            'lostFoundObj': '招领信息',
            'title': '标题',
            'contents': '表扬内容',
            'addTime': '表扬时间',
        }
        pf = pf[columns_map.keys()]
        pf.rename(columns=columns_map, inplace=True)
        # 将空的单元格替换为空字符
        pf.fillna('', inplace=True)
        #设定文件名和导出路径
        filename = 'praises.xlsx'
        # 这个路径可以在settings中设置也可以直接手动输入
        root_path = settings.MEDIA_ROOT + '/output/'
        file_path = os.path.join(root_path, filename)
        pf.to_excel(file_path, encoding='utf-8', index=False)
        # 将生成的excel文件输出到网页下载
        file = open(file_path, 'rb')
        response = FileResponse(file)
        response['Content-Type'] = 'application/octet-stream'
        response['Content-Disposition'] = 'attachment;filename="praises.xlsx"'
        return response


PythonProject/templates/Praise/praise_frontquery_result.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>表扬查询</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
<div class="container">
{% include 'header.html' %}
	<div class="row"> 
	<div class="col-md-3 wow fadeInLeft">
		<div class="page-header">
    		<h1>表扬查询</h1>
		</div>
		<form name="praiseQueryForm" id="praiseQueryForm" action="{% url 'Praise:frontList' %}" class="mar_t15" method="post">
			 {% csrf_token %}
            <div class="form-group">
            	<label for="lostFoundObj_lostFoundId">招领信息：</label>
                <select id="lostFoundObj_lostFoundId" name="lostFoundObj.lostFoundId" class="form-control">
                	<option value="0">不限制</option>
                    {% for lostFound in lostFounds %}
                        {% if lostFound.lostFoundId == lostFoundObj_lostFoundId %}
                             <option value="{{ lostFound.lostFoundId }}" selected>{{ lostFound.title }}</option>
                        {% else %}
                            <option value="{{ lostFound.lostFoundId }}">{{ lostFound.title }}</option>
                        {% endif %}
                    {% endfor %}
 			</select>
            </div>
			<div class="form-group">
				<label for="title">标题:</label>
				<input type="text" id="title" name="title" value="{{ title }}" class="form-control" placeholder="请输入标题">
			</div>
			<div class="form-group">
				<label for="addTime">表扬时间:</label>
				<input type="text" id="addTime" name="addTime" class="form-control"  placeholder="请选择表扬时间" value="{{ addTime }}" onclick="SelectDate(this,'yyyy-MM-dd')" />
			</div>
            <input type=hidden name=currentPage value="{{ currentPage }}" />
            <button type="submit" class="btn btn-primary">查询</button>
        </form>
	</div>

		<div class="col-md-9 wow fadeInDown" data-wow-duration="0.5s">
			<div>
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
			    	<li><a href="{% url 'Index:index' %}">首页</a></li>
			    	<li role="presentation" class="active"><a href="#praiseListPanel" aria-controls="praiseListPanel" role="tab" data-toggle="tab">表扬列表</a></li>
			    	<li role="presentation" ><a href="{% url 'Praise:frontAdd' %}" style="display:none;">添加表扬</a></li>
				</ul>
			  	<!-- Tab panes -->
			  	<div class="tab-content">
				    <div role="tabpanel" class="tab-pane active" id="praiseListPanel">
				    		<div class="row">
				    			<div class="col-md-12 top5">
				    				<div class="table-responsive">
				    				<table class="table table-condensed table-hover">
				    					<tr class="success bold"><td>序号</td><td>表扬id</td><td>招领信息</td><td>标题</td><td>表扬内容</td><td>表扬时间</td><td>操作</td></tr>
                                        {% for praise in praises_page %}
 										<tr>
 											<td>{{ startIndex|add:forloop.counter }}</td>
 											<td>{{ praise.praiseId }}</td>
 											<td>{{ praise.lostFoundObj.title }}</td>
 											<td>{{ praise.title }}</td>
 											<td>{{ praise.contents }}</td>
 											<td>{{ praise.addTime }}</td>
 											<td>
 												<a href="{% url 'Praise:frontShow' praise.praiseId  %}"><i class="fa fa-info"></i>&nbsp;查看</a>&nbsp;
 												<a href="#" onclick="praiseEdit('{{ praise.praiseId }}');" style="display:none;"><i class="fa fa-pencil fa-fw"></i>编辑</a>&nbsp;
 												<a href="#" onclick="praiseDelete('{{ praise.praiseId }}');" style="display:none;"><i class="fa fa-trash-o fa-fw"></i>删除</a>
 											</td> 
 										</tr>
 										{% endfor %}
				    				</table>
				    				</div>
				    			</div>
				    		</div>

				    		<div class="row">
					            <div class="col-md-12">
						            <nav class="pull-left">
						                <ul class="pagination">
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:-1 }},{{ totalPage }}>);" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                                            {% for page in pageList %}
                                            {% if currentPage == page %}
						                        <li class="active"><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
						                    {% else %}
                                                <li><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
                                            {% endif %}
                                            {% endfor %}
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:1 }},{{ totalPage }});"><span aria-hidden="true">&raquo;</span></a></li>
						                </ul>
						            </nav>
						            <div class="pull-right" style="line-height:75px;" >共有{{ recordNumber }}条记录，当前第{{ currentPage }}/{{ totalPage }} 页</div>
					            </div>
				            </div> 
				    </div>
				</div>
			</div>
		</div>
		</div>
	</div> 
<div id="praiseEditDialog" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><i class="fa fa-edit"></i>&nbsp;表扬信息编辑</h4>
      </div>
      <div class="modal-body" style="height:450px; overflow: scroll;">
      	<form class="form-horizontal" name="praiseEditForm" id="praiseEditForm" enctype="multipart/form-data" method="post"  class="mar_t15">
		    {% csrf_token %}
		  <div class="form-group">
			 <label for="praise_praiseId_edit" class="col-md-3 text-right">表扬id:</label>
			 <div class="col-md-9"> 
			 	<input type="text" id="praise_praiseId_edit" name="praise.praiseId" class="form-control" placeholder="请输入表扬id" readOnly>
			 </div>
		  </div> 
		  <div class="form-group">
		  	 <label for="praise_lostFoundObj_lostFoundId_edit" class="col-md-3 text-right">招领信息:</label>
		  	 <div class="col-md-9">
			    <select id="praise_lostFoundObj_lostFoundId_edit" name="praise.lostFoundObj.lostFoundId" class="form-control">
                    {% for lostFound in lostFounds %}
                        <option value="{{ lostFoundObj.lostFoundId }}">{{ lostFoundObj.title }}</option>
                    {% endfor %}
			    </select>
		  	 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="praise_title_edit" class="col-md-3 text-right">标题:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="praise_title_edit" name="praise.title" class="form-control" placeholder="请输入标题">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="praise_contents_edit" class="col-md-3 text-right">表扬内容:</label>
		  	 <div class="col-md-9">
			    <textarea id="praise_contents_edit" name="praise.contents" rows="8" class="form-control" placeholder="请输入表扬内容"></textarea>
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="praise_addTime_edit" class="col-md-3 text-right">表扬时间:</label>
		  	 <div class="col-md-9">
                <div class="input-group date praise_addTime_edit col-md-12" data-link-field="praise_addTime_edit">
                    <input class="form-control" id="praise_addTime_edit" name="praise.addTime" size="16" type="text" value="" placeholder="请选择表扬时间" readonly>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                </div>
		  	 </div>
		  </div>
		</form> 
	    <style>#praiseEditForm .form-group {margin-bottom:5px;}  </style>
      </div>
      <div class="modal-footer"> 
      	<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
      	<button type="button" class="btn btn-primary" onclick="ajaxPraiseModify();">提交</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jsdate.js' %}"></script>
<script>
/*跳转到查询结果的某页*/
function GoToPage(currentPage,totalPage) {
    if(currentPage==0) return;
    if(currentPage>totalPage) return;
    document.praiseQueryForm.currentPage.value = currentPage;
    document.praiseQueryForm.submit();
}

/*可以直接跳转到某页*/
function changepage(totalPage)
{
    var pageValue=document.praiseQueryForm.pageValue.value;
    if(pageValue>totalPage) {
        alert('你输入的页码超出了总页数!');
        return ;
    }
    document.praiseQueryForm.currentPage.value = pageValue;
    documentpraiseQueryForm.submit();
}

/*弹出修改表扬界面并初始化数据*/
function praiseEdit(praiseId) {
	$.ajax({
		url :  '/Praise/update/' + praiseId,
		type : "get",
		dataType: "json",
		success : function (praise, response, status) {
			if (praise) {
				$("#praise_praiseId_edit").val(praise.praiseId);
				$.ajax({
					url: "{% url 'LostFound:listAll' %}",
					type: "get",
					success: function(lostFounds,response,status) { 
						$("#praise_lostFoundObj_lostFoundId_edit").empty();
						var html="";
		        		$(lostFounds).each(function(i,lostFound){
		        			html += "<option value='" + lostFound.lostFoundId + "'>" + lostFound.title + "</option>";
		        		});
		        		$("#praise_lostFoundObj_lostFoundId_edit").html(html);
		        		$("#praise_lostFoundObj_lostFoundId_edit").val(praise.lostFoundObjPri);
					}
				});
				$("#praise_title_edit").val(praise.title);
				$("#praise_contents_edit").val(praise.contents);
				$("#praise_addTime_edit").val(praise.addTime);
				$('#praiseEditDialog').modal('show');
			} else {
				alert("获取信息失败！");
			}
		}
	});
}

/*删除表扬信息*/
function praiseDelete(praiseId) {
    var csrf = $('input[name="csrfmiddlewaretoken"]').val();
	if(confirm("确认删除这个记录")) {
		$.ajax({
			type : "POST",
			url : "/Praise/deletes",
			data : {
				praiseIds : praiseId,
                "csrfmiddlewaretoken": csrf
			},
			success : function (obj) {
				if (obj.success) {
					alert("删除成功");
					$("#praiseQueryForm").submit();
					//location.href= basePath + "Praise/frontlist";
				}
				else 
					alert(obj.message);
			},
		});
	}
}

/*ajax方式提交表扬信息表单给服务器端修改*/
function ajaxPraiseModify() {
	$.ajax({
		url :   '/Praise/update/' + $("#praise_praiseId_edit").val(),
		type : "post",
		dataType: "json",
		data: new FormData($("#praiseEditForm")[0]),
		success : function (obj, response, status) {
            if(obj.success){
                alert("信息修改成功！");
                $("#praiseQueryForm").submit();
            }else{
                alert(obj.message);
            } 
		},
		processData: false,
		contentType: false,
	});
}

$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();

    /*表扬时间组件*/
    $('.praise_addTime_edit').datetimepicker({
    	language:  'zh-CN',  //语言
    	format: 'yyyy-mm-dd hh:ii:ss',
    	weekStart: 1,
    	todayBtn:  1,
    	autoclose: 1,
    	minuteStep: 1,
    	todayHighlight: 1,
    	startView: 2,
    	forceParse: 0
    });
})
</script>
</body>
</html>
